site_name: Monitoring and Logging on Karbon
site_url: https://github.com/nutanix-japan/Karbon_Monitoring_Logging_Material
site_author: Lakshmi Balaramane

# Repository

repo_name: nutanix-japan/Karbon_Monitoring_Logging_Material
repo_url: https://github.com/nutanix-japan/Karbon_Monitoring_Logging_Material

# Copyright
copyright: Copyright &copy; 2016 - 2022 Nutanix APAC Enablement Practice

# Configuration

theme:
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
  - navigation.instant
  - navigation.tracking
  # - navigation.sections # leave this commented for sections
  - navigation.expand
  - navigation.top
  - navigation.integrate
  - search.highlight
  - search.suggest
  - toc.follow
  palette:

    #Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
plugins:
    - search

# Style sheeting here
# extra_css:
#   - stylesheets/extra.css

# Site navigation

nav:
    - Home: index.md
    - 'Creating a Karbon K8S cluster': appendix/create_kube.md
    - 'Monitoring':
       - 'Monitoring in Nutanix Karbon': promgraf/promgraf.md
       - 'Exploring Monitoring Resources': explore/explore.md
       - 'Installing Grafana in Karbon': connect/connect.md
       - 'Visualising Metrics in Karbon': visualise/visualise.md
       - 'Cleaning up and Takeaways': cleanup/cleanup.md
    - 'Logging': 
       - 'Logging in Nutanix Karbon': logging/logging.md
    - 'Appendix': 
        - 'Creating Linux Tools VM': appendix/linux_tools_vm.md
        - 'Helm': appendix/helm.md
        
        

